#!/usr/bin/env node
/**
 * Acute — public status dashboard build script (zero dependencies, Node 18+).
 *
 *   inputs:   data.json · usage.json (optional) · src/template.html ·
 *             src/usage-template.html · src/style.css · src/usage.css ·
 *             src/app.js · src/usage.js
 *   outputs:  index.html · usage.html · assets/style.css · assets/usage.css ·
 *             assets/app.js · assets/usage.js
 *
 * How it works
 *   1. data.json is the single source of content truth (curated, public-safe).
 *      usage.json (generated by ACUTE-CODE's scripts/export-usage.mjs) feeds
 *      the usage page; when absent the page renders an empty state.
 *   2. Loop-shaped sections (pillars, features, plan, quality, milestones,
 *      principles, chips, stats, docs) are rendered into escaped HTML fragments.
 *   3. Fragments + literals are injected into src/template.html and
 *      src/usage-template.html at {{PLACEHOLDER}} slots (function replacers
 *      only — never string interpolation into .replace, so "$&"-style
 *      content can't corrupt it).
 *   4. CSS/JS are copied to assets/ and referenced with a cache-busting
 *      query so repeat visitors always get fresh output after a rebuild.
 *   5. FAIL-CLOSED DENYLIST: the site deploys to a PUBLIC GitHub Pages repo,
 *      so every output file (and the committed usage.json itself) is scanned
 *      for token / credential / internal-path / internal-id patterns. Any
 *      hit aborts the build with exit 1 BEFORE anything is written or
 *      published.
 *
 * Usage:  node build.mjs
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)));
const read = (...p) => readFileSync(join(ROOT, ...p), "utf8");

/* ── inputs ─────────────────────────────────────────────────────────────── */
const data = JSON.parse(read("data.json"));
const template = read("src", "template.html");
const css = read("src", "style.css");
const js = read("src", "app.js");

/* ── basic validation ───────────────────────────────────────────────────── */
for (const key of ["product", "pillars", "plan", "quality", "milestones", "chips", "audit"]) {
  if (data[key] === undefined) {
    console.error(`data.json is missing required field: ${key}`);
    process.exit(1);
  }
}
const audit = data.audit;
for (const key of ["benchmark", "capabilities", "tracks", "sequence", "decisions"]) {
  if (!Array.isArray(audit[key]) || audit[key].length === 0) {
    console.error(`data.json: audit.${key} must be a non-empty array`);
    process.exit(1);
  }
}
for (const key of ["p0", "p1", "p2"]) {
  if (!Array.isArray(audit.gaps?.[key]) || audit.gaps[key].length === 0) {
    console.error(`data.json: audit.gaps.${key} must be a non-empty array`);
    process.exit(1);
  }
}
if (!Array.isArray(data.pillars) || data.pillars.length === 0) {
  console.error("data.json: pillars must be a non-empty array");
  process.exit(1);
}
if (!Array.isArray(data.features) || data.features.length === 0) {
  console.error("data.json: features must be a non-empty array");
  process.exit(1);
}
if (!Array.isArray(data.documentation) || data.documentation.length === 0) {
  console.error("data.json: documentation must be a non-empty array");
  process.exit(1);
}

/* ── helpers ────────────────────────────────────────────────────────────── */
const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
const clamp = (n, lo, hi) => Math.min(hi, Math.max(lo, n));
const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0);

const buildDate = new Date();
const buildIso = buildDate.toISOString();
const buildStamp = buildIso.replace("T", " ").slice(0, 16) + " UTC";
const cacheBust = buildIso.replace(/[^0-9A-Za-z]/g, "").toLowerCase();

const prettyDate = (iso) => {
  const d = new Date(`${iso}T00:00:00Z`);
  return Number.isNaN(d.getTime())
    ? String(iso)
    : d.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
};

/* ── derived values ─────────────────────────────────────────────────────── */
const product = data.product;
const pillars = data.pillars;
const plan = data.plan;
const quality = data.quality;
const suites = Array.isArray(quality.suites) ? quality.suites : [];
const milestones = [...(Array.isArray(data.milestones) ? data.milestones : [])]
  .sort((a, b) => String(a.date).localeCompare(String(b.date)));
const features = Array.isArray(data.features) ? data.features : [];
const documentation = Array.isArray(data.documentation) ? data.documentation : [];
const gaps = audit.gaps ?? { p0: [], p1: [], p2: [] };
const gapTotal = gaps.p0.length + gaps.p1.length + gaps.p2.length;

const totalTests = suites.reduce((n, s) => n + num(s.tests), 0);
const totalSkipped = suites.reduce((n, s) => n + num(s.skipped), 0);
const maxSuite = Math.max(1, ...suites.map((s) => num(s.tests)));
const ciOk = quality.ci === "success" || quality.ci === "green";
const ciBad = quality.ci === "failure" || quality.ci === "failing" || quality.ci === "red";
const lintOk = quality.lint === "clean" || quality.lint === "success";
const typecheckOk = quality.typecheck === "clean" || quality.typecheck === "success";
const cargoOk = quality.cargoCheck === "green" || quality.cargoCheck === "success";
const cargoBad = quality.cargoCheck === "failing" || quality.cargoCheck === "failure";
const license = quality.licenseAudit ?? { deps: 0, verdict: "n/a" };

const topPillar = pillars.reduce(
  (best, p) => (num(p.progress) > num(best.progress) ? p : best),
  pillars[0],
);
const topPillarState = String(topPillar.state ?? "");

const firstMs = milestones[0];
const lastMs = milestones[milestones.length - 1];
let spanDays = 0;
if (firstMs && lastMs) {
  const a = Date.parse(`${firstMs.date}T00:00:00Z`);
  const b = Date.parse(`${lastMs.date}T00:00:00Z`);
  if (!Number.isNaN(a) && !Number.isNaN(b)) {
    spanDays = Math.round((b - a) / 86400000) + 1;
  }
}

/* ── icons (inline SVG, stroke style — no external assets) ──────────────── */
const svg = (inner) =>
  `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ` +
  `stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${inner}</svg>`;

const ICONS = {
  coding: svg(
    '<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>',
  ),
  agentic: svg(
    '<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/>' +
    '<line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/>',
  ),
  automation: svg(
    '<rect width="8" height="8" x="3" y="3" rx="2"/><path d="M7 11v4a2 2 0 0 0 2 2h4"/>' +
    '<rect width="8" height="8" x="13" y="13" rx="2"/>',
  ),
  check: svg(
    '<path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/>' +
    '<path d="m9 12 2 2 4-4"/>',
  ),
  terminal: svg(
    '<polyline points="4 17 10 11 4 5"/><line x1="12" x2="20" y1="19" y2="19"/>',
  ),
  package: svg(
    '<path d="M16.5 9.4 7.55 4.24"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.29 7 12 12 20.71 7"/><line x1="12" x2="12" y1="22" y2="12"/>',
  ),
  // feature-card icons
  browser: svg(
    '<rect x="3" y="4" width="18" height="16" rx="2"/>' +
    '<path d="M3 9h18"/>' +
    '<circle cx="6.5" cy="6.5" r="0.6" fill="currentColor"/>' +
    '<circle cx="9" cy="6.5" r="0.6" fill="currentColor"/>',
  ),
  panels: svg(
    '<rect x="3" y="4" width="18" height="16" rx="2"/>' +
    '<line x1="15" y1="4" x2="15" y2="20"/>' +
    '<line x1="3" y1="9" x2="15" y2="9"/>' +
    '<line x1="3" y1="13" x2="15" y2="13"/>' +
    '<line x1="3" y1="17" x2="15" y2="17"/>',
  ),
  bell: svg(
    '<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/>' +
    '<path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>',
  ),
  agents: svg(
    '<circle cx="12" cy="8" r="3"/>' +
    '<circle cx="5" cy="18" r="3"/>' +
    '<circle cx="19" cy="18" r="3"/>' +
    '<line x1="10.5" y1="10" x2="6.5" y2="16"/>' +
    '<line x1="13.5" y1="10" x2="17.5" y2="16"/>',
  ),
  shield: svg(
    '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>' +
    '<path d="m9 12 2 2 4-4"/>',
  ),
  plug: svg(
    '<path d="M12 22v-5"/><path d="M9 8V2"/><path d="M15 8V2"/><path d="M18 8v5a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V8Z"/>',
  ),
  command: svg(
    '<path d="M9 6a3 3 0 1 0 0 6h6a3 3 0 1 0 0-6"/>' +
    '<path d="M9 18a3 3 0 1 1 0-6h6a3 3 0 1 1 0 6"/>' +
    '<line x1="12" y1="6" x2="12" y2="18"/>',
  ),
  index: svg(
    '<path d="M4 6h2v12H4z"/><path d="M7 9h13"/>' +
    '<path d="M7 13h13"/><path d="M7 17h13"/><path d="M7 6h6"/>',
  ),
  globe: svg(
    '<circle cx="12" cy="12" r="10"/>' +
    '<line x1="2" y1="12" x2="22" y2="12"/>' +
    '<path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>',
  ),
  stream: svg(
    '<path d="M3 12h4l3-8 4 16 3-8h4"/>',
  ),
  doc: svg(
    '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>' +
    '<polyline points="14 2 14 8 20 8"/>' +
    '<line x1="8" y1="13" x2="16" y2="13"/>' +
    '<line x1="8" y1="17" x2="13" y2="17"/>',
  ),
  arrow: svg(
    '<line x1="5" y1="12" x2="19" y2="12"/>' +
    '<polyline points="12 5 19 12 12 19"/>',
  ),
};

/* ── fragment renderers ─────────────────────────────────────────────────── */
/* ── audit renderers ────────────────────────────────────────────────────── */
const scoreBar = (score, max) => {
  const pct = clamp(Math.round((num(score) / max) * 100), 0, 100);
  const lvl = num(score) <= 1 ? " low" : num(score) >= 3 ? " high" : "";
  return `<span class="bench-score"><span class="bench-score-track"><span class="bench-score-fill${lvl}" style="--w:${pct}%"></span></span><span class="bench-score-num mono">${num(score)}/${max}</span></span>`;
};

const renderBenchRow = (b) => `      <div class="bench-row" role="row">
        <span class="bench-dim" role="rowheader">${esc(b.dimension)}</span>
        <span class="bench-acute" role="cell">${scoreBar(b.acute, 5)}</span>
        <span class="bench-best" role="cell"><span class="bench-best-name">${esc(b.bestName)}</span>${scoreBar(b.bestScore, 5)}</span>
        <span class="bench-verdict" role="cell">${esc(b.verdict)}</span>
      </div>`;

const CAP_STATUS = {
  live: { cls: "cap-live", label: "live" },
  partial: { cls: "cap-partial", label: "partial" },
  missing: { cls: "cap-missing", label: "missing" },
};

const renderCapability = (c) => {
  const st = CAP_STATUS[c.status] ?? { cls: "cap-missing", label: esc(c.status) };
  return `      <article class="cap-card card">
        <div class="cap-top">
          <h3 class="cap-title">${esc(c.area)}</h3>
          <span class="cap-status ${st.cls}">${st.label}</span>
        </div>
        <p class="cap-note">${esc(c.note)}</p>
      </article>`;
};

const impactCls = (v) => (String(v).toUpperCase() === "HIGH" ? "chip-impact-high" : "chip-impact-med");
const effortCls = (v) => {
  const s = String(v).toUpperCase();
  return s === "S" ? "chip-effort-s" : s === "M" ? "chip-effort-m" : "chip-effort-l";
};

const renderGapItem = (g) => `        <article class="gap-item">
          <div class="gap-item-head">
            <span class="gap-id mono">${esc(g.id)}</span>
            <h4 class="gap-title">${esc(g.title)}</h4>
            <span class="gap-chips">
              <span class="gap-chip ${impactCls(g.impact)}">${esc(g.impact)}</span>
              <span class="gap-chip ${effortCls(g.effort)}">${esc(g.effort)}</span>
            </span>
          </div>
          <p class="gap-why">${esc(g.why)}</p>
        </article>`;

const renderTrack = (t) => `      <article class="track-card card">
        <header class="track-head">
          <span class="track-id mono">${esc(t.id)}</span>
          <div>
            <h3 class="track-name">${esc(t.name)}</h3>
            <p class="track-tagline">${esc(t.tagline)}</p>
          </div>
        </header>
        <ul class="track-contents">
${t.contents.map((c) => `          <li>${esc(c)}</li>`).join("\n")}
        </ul>
        <div class="track-gets">
          <span class="track-gets-label">Owner gets</span>
          <p>${esc(t.gets)}</p>
        </div>
        <footer class="track-meta">
          <span class="track-meta-chip"><span class="track-meta-label">rounds</span> ${esc(t.rounds)}</span>
          <span class="track-meta-chip"><span class="track-meta-label">deps</span> ${esc(t.deps)}</span>
        </footer>
      </article>`;

const renderSeq = (s) => `      <li class="seq-item">
        <span class="seq-round mono">${esc(s.round)}</span>
        <div class="seq-body">
          <span class="seq-track">${esc(s.track)}</span>
          <p class="seq-why">${esc(s.why)}</p>
        </div>
      </li>`;

const renderDecision = (d) => `      <article class="decision-card card">
        <span class="decision-num mono" aria-hidden="true">${String(d.n).padStart(2, "0")}</span>
        <div class="decision-body">
          <h3 class="decision-title">${esc(d.title)}</h3>
          <p class="decision-detail">${esc(d.detail)}</p>
          <p class="decision-rec"><span class="decision-rec-label">Recommended</span>${esc(d.recommend)}</p>
        </div>
      </article>`;

const STATES = {
  usable: { cls: "state-usable", label: "Usable" },
  building: { cls: "state-building", label: "Building" },
  planned: { cls: "state-planned", label: "Planned" },
};

const renderPillar = (p, i) => {
  const state = STATES[p.state] ?? { cls: "state-planned", label: esc(p.state) };
  const pct = clamp(num(p.progress), 0, 100);
  const icon = ICONS[p.id] ?? ICONS.coding;
  return `      <article class="pillar-card card" data-state="${esc(p.state)}">
        <div class="pillar-top">
          <span class="pillar-icon">${icon}</span>
          <h3 class="pillar-title">${esc(p.title)}</h3>
          <span class="state-badge ${state.cls}">${state.label}</span>
        </div>
        <div class="pillar-progress-row">
          <span class="pillar-progress-label">Pillar progress</span>
          <span class="pillar-pct"><span data-count="${pct}">${pct}</span>%</span>
        </div>
        <div class="bar" role="progressbar" aria-valuenow="${pct}" aria-valuemin="0" aria-valuemax="100" aria-label="${esc(p.title)} progress">
          <div class="bar-fill" data-progress="${pct}" style="--w:${pct}%"></div>
        </div>
        <p class="pillar-summary">${esc(p.summary)}</p>
      </article>`;
};

const FEATURE_STATUS = {
  live: { cls: "feature-status", label: "live" },
  beta: { cls: "feature-status", label: "beta" },
  planned: { cls: "feature-status", label: "planned" },
};

const renderFeature = (f) => {
  const st = FEATURE_STATUS[f.status] ?? { cls: "feature-status", label: esc(f.status) };
  const icon = ICONS[f.icon] ?? ICONS.command;
  return `      <article class="feature-card card">
        <div class="feature-top">
          <span class="feature-icon">${icon}</span>
          <h3 class="feature-title">${esc(f.title)}</h3>
          <span class="${st.cls}">${st.label}</span>
        </div>
        <p class="feature-desc">${esc(f.desc)}</p>
      </article>`;
};

const renderDoc = (d) => {
  const icon = ICONS.doc;
  return `      <article class="doc-card card">
        <div class="doc-top">
          <span class="doc-category">${esc(d.category)}</span>
          <span class="doc-arrow" aria-hidden="true">${ICONS.arrow}</span>
        </div>
        <h3 class="doc-title">${esc(d.title)}</h3>
        <p class="doc-desc">${esc(d.desc)}</p>
        <code class="doc-path">${esc(d.path)}</code>
      </article>`;
};

const renderStat = (stat) => `      <article class="stat-card card">
        <span class="stat-label">${esc(stat.label)}</span>
        <span class="stat-value"><span data-count="${num(stat.value)}">${num(stat.value)}</span>${stat.suffix ? esc(stat.suffix) : ""}</span>
        <span class="stat-sub">${esc(stat.sub)}</span>
      </article>`;

const stats = [
  {
    label: "Tests passing",
    value: totalTests,
    suffix: "",
    sub: `${suites.length} suites · ${totalSkipped} skipped · unit + e2e`,
  },
  {
    label: "Audit gaps identified",
    value: gapTotal,
    suffix: "",
    sub: `9 critical · 15 high-impact · 13 next — six-track roadmap below`,
  },
  {
    label: "Milestones shipped",
    value: milestones.length,
    suffix: "",
    sub: firstMs && lastMs
      ? `${prettyDate(firstMs.date)} – ${prettyDate(lastMs.date)}${spanDays ? ` · ${spanDays}-day run` : ""}`
      : "",
  },
  {
    label: "Dependencies audited",
    value: num(license.deps),
    suffix: "",
    sub: `license audit · ${esc(license.verdict)}`,
  },
];

const PLAN_STATUS = {
  "in-progress": { cls: "status-inprogress", label: "in progress" },
  "owner-gated": { cls: "status-ownergated", label: "owner-gated" },
  planned: { cls: "status-planned", label: "planned" },
};

const renderUpcoming = (item) => {
  const s = PLAN_STATUS[item.status] ?? { cls: "status-planned", label: esc(item.status) };
  return `      <li class="upcoming-item">
        <span class="status-chip ${s.cls}">${s.label}</span>
        <div class="upcoming-body">
          <span class="upcoming-phase">${esc(item.phase)}</span>
          <span class="upcoming-note">${esc(item.note)}</span>
        </div>
      </li>`;
};

const renderSuite = (s) => {
  const tests = num(s.tests);
  const pct = clamp(Math.round((tests / maxSuite) * 100), 3, 100);
  const skip = num(s.skipped);
  const skipStr = skip > 0
    ? ` · <span class="suite-skip">${skip} skipped</span>`
    : "";
  return `        <div class="suite-row">
          <div class="suite-head">
            <span class="suite-name">${esc(s.name)}</span>
            <span class="suite-count"><strong data-count="${tests}">${tests}</strong> tests${skipStr}</span>
          </div>
          <div class="bar suite-bar" role="progressbar" aria-valuenow="${tests}" aria-valuemin="0" aria-valuemax="${maxSuite}" aria-label="${esc(s.name)} test count relative to largest suite">
            <div class="bar-fill" data-progress="${pct}" style="--w:${pct}%"></div>
          </div>
        </div>`;
};

const renderCheck = (icon, iconCls, label, value, ok, sub, bad = false) => `        <article class="check-card card">
          <span class="check-icon ${iconCls}">${icon}</span>
          <div class="check-body">
            <span class="check-label">${esc(label)}</span>
            <span class="check-value ${ok ? "value-ok" : bad ? "value-bad" : ""}">${esc(value)}</span>
            <span class="check-sub">${esc(sub)}</span>
          </div>
        </article>`;

const checks = [
  renderCheck(
    ICONS.check,
    ciOk ? "icon-ok" : ciBad ? "icon-bad" : "icon-accent",
    "CI pipeline",
    ciOk ? "passing" : ciBad ? "failing" : String(quality.ci),
    ciOk,
    ciOk ? "latest run: success" : "red since R39 — Rust shell, fix queued (P0-1)",
    ciBad,
  ),
  renderCheck(
    ICONS.terminal,
    lintOk ? "icon-ok" : "icon-accent",
    "Lint (eslint)",
    lintOk ? "clean" : String(quality.lint),
    lintOk,
    "0 errors, 0 warnings",
  ),
  renderCheck(
    ICONS.command,
    typecheckOk ? "icon-ok" : "icon-accent",
    "Typecheck (tsc)",
    typecheckOk ? "clean" : String(quality.typecheck),
    typecheckOk,
    "strict mode, no any",
  ),
  renderCheck(
    ICONS.package,
    cargoOk ? "icon-ok" : cargoBad ? "icon-bad" : "icon-accent",
    "cargo check",
    cargoOk ? "passing" : cargoBad ? "failing" : String(quality.cargoCheck),
    cargoOk,
    cargoOk ? "Rust shell compiles clean" : "Rust shell — one-line Tauri API fix identified (Track 1)",
    cargoBad,
  ),
  renderCheck(
    ICONS.shield,
    license.verdict === "CLEAN" ? "icon-ok" : "icon-accent",
    "License audit",
    String(license.verdict),
    license.verdict === "CLEAN",
    `${num(license.deps)} dependencies reviewed`,
  ),
];

const renderMilestone = (m, isLatest) => `        <li class="timeline-item${isLatest ? " latest" : ""}">
          <span class="timeline-date">${esc(m.date)}</span>
          <span class="timeline-label">${esc(m.label)}</span>
          ${isLatest ? '<span class="timeline-flag">latest</span>' : ""}
        </li>`;

const renderPrinciple = (text, i) => {
  const raw = String(text);
  const sep = raw.indexOf(" — ");
  const title = sep >= 0 ? raw.slice(0, sep) : raw;
  const desc = sep >= 0 ? raw.slice(sep + 3) : "";
  const idx = String(i + 1).padStart(2, "0");
  return `      <article class="principle-card card">
        <span class="principle-index" aria-hidden="true">${idx}</span>
        <span class="principle-rule" aria-hidden="true"></span>
        <h3 class="principle-title">${esc(title)}</h3>
        ${desc ? `<p class="principle-desc">${esc(desc)}</p>` : ""}
      </article>`;
};

const renderTechChip = (c) => `        <span class="tech-chip"><span class="tech-dot" aria-hidden="true"></span>${esc(c)}</span>`;

/* ── assemble the page ──────────────────────────────────────────────────── */
const title = `${product.name} — status dashboard`;
const description = `${product.tagline}. Public status: pillars, features, plan, quality metrics, milestones, docs.`;
const pageUrl = "https://testplay-byte.github.io/DASHBOARD/";
const favicon =
  "data:image/svg+xml," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">' +
    '<rect width="64" height="64" rx="14" fill="#FF6B2C"/>' +
    '<text x="32" y="45" font-family="Menlo, Consolas, monospace" font-size="34" ' +
    'font-weight="700" text-anchor="middle" fill="#1f130a">◐</text></svg>',
  );
const statusPill = ciOk
  ? "All systems healthy"
  : ciBad
    ? "CI red since R39 — Rust fix queued (Track 1)"
    : "Status: check runs";
const statusShort = ciOk ? "healthy" : ciBad ? "attention" : "watch";
const statusPillClass = ciOk ? "pill-ok" : ciBad ? "pill-warn" : "pill-ok";

// Public-safe GitHub link — the denylist allows github.com/testplay-byte/DASHBOARD
// (the public repo we publish to). We never link the private source repo here.
const githubUrl = "https://github.com/testplay-byte/DASHBOARD";
const githubLabel = "testplay-byte/DASHBOARD";

const footerNote =
  `Generated ${buildStamp} · curated public data only — no product source ` +
  `· ${esc(product.name)} v${esc(product.version)}`;

const dataJson = JSON.stringify({
  buildIso,
  screenshots: data.screenshots ?? null,
}).replace(/</g, "\\u003c");

const slots = {
  LANG: "en",
  TITLE: esc(title),
  DESCRIPTION: esc(description),
  PAGE_URL: esc(pageUrl),
  FAVICON: favicon,
  CSS_URL: `assets/style.css?v=${cacheBust}`,
  JS_URL: `assets/app.js?v=${cacheBust}`,
  PRODUCT_NAME: esc(product.name),
  VERSION: esc(product.version),
  TAGLINE: esc(product.tagline),
  AVAILABILITY: esc(product.availability),
  STATUS_PILL: esc(statusPill),
  STATUS_SHORT: esc(statusShort),
  STATUS_PILL_CLASS: statusPillClass,
  GITHUB_URL: esc(githubUrl),
  GITHUB_LABEL: esc(githubLabel),
  BUILD_STAMP: esc(buildStamp),
  STATS: stats.map(renderStat).join("\n"),
  PILLARS: pillars.map(renderPillar).join("\n"),
  FEATURES: features.map(renderFeature).join("\n"),
  NOW_TITLE: esc(plan.current.title),
  NOW_DETAIL: esc(plan.current.detail),
  UPCOMING: (plan.upcoming ?? []).map(renderUpcoming).join("\n"),
  AUDIT_METHOD: esc(audit.method ?? ""),
  AUDIT_VISION: esc(audit.vision ?? ""),
  AUDIT_COMPOSITE: esc(audit.headline?.composite ?? ""),
  AUDIT_FRONTIER: esc(audit.headline?.frontier ?? ""),
  AUDIT_VERDICT: esc(audit.headline?.verdict ?? ""),
  BENCH_ROWS: audit.benchmark.map(renderBenchRow).join("\n"),
  CAPABILITIES: audit.capabilities.map(renderCapability).join("\n"),
  GAP_TOTAL: gapTotal,
  P0_COUNT: gaps.p0.length,
  P1_COUNT: gaps.p1.length,
  P2_COUNT: gaps.p2.length,
  P0_INTRO: esc(gaps.p0_intro ?? ""),
  P1_INTRO: esc(gaps.p1_intro ?? ""),
  P2_INTRO: esc(gaps.p2_intro ?? ""),
  P0_ITEMS: gaps.p0.map(renderGapItem).join("\n"),
  P1_ITEMS: gaps.p1.map(renderGapItem).join("\n"),
  P2_ITEMS: gaps.p2.map(renderGapItem).join("\n"),
  TRACKS: audit.tracks.map(renderTrack).join("\n"),
  SEQUENCE: audit.sequence.map(renderSeq).join("\n"),
  DECISIONS: audit.decisions.map(renderDecision).join("\n"),
  CI_NOTE: esc(quality.ciNote ?? ""),
  QUALITY_SUITES: suites.map(renderSuite).join("\n"),
  QUALITY_CHECKS: checks.join("\n"),
  TOTAL_TESTS: totalTests,
  SKIPPED_TESTS: totalSkipped,
  DOCUMENTATION: documentation.map(renderDoc).join("\n"),
  MILESTONES: milestones.map((m, i) => renderMilestone(m, i === milestones.length - 1)).join("\n"),
  PRINCIPLES: (plan.principles ?? []).map(renderPrinciple).join("\n"),
  TECH_CHIPS: (data.chips ?? []).map(renderTechChip).join("\n"),
  FOOTER_NOTE: esc(footerNote),
  DATA_JSON: dataJson,
};

let missing = [];
let html = template.replace(/\{\{([A-Z0-9_]+)\}\}/g, (match, name) => {
  if (!(name in slots)) {
    missing.push(name);
    return match;
  }
  return slots[name];
});
if (missing.length) {
  console.error(`template placeholders without a value: ${missing.join(", ")}`);
  process.exit(1);
}
const unused = Object.keys(slots).filter((k) => !template.includes(`{{${k}}}`));
if (unused.length) {
  console.warn(`warning: unused slots (fine, just informational): ${unused.join(", ")}`);
}

/* ════════════════════════════════════════════════════════════════════════ */
/* ── usage page (R51-e) — renders src/usage-template.html from usage.json ── */
/* ════════════════════════════════════════════════════════════════════════ */

const usageTemplate = read("src", "usage-template.html");
const usageCss = read("src", "usage.css");
const usageJs = read("src", "usage.js");

/* usage.json is a generated file (ACUTE-CODE: node scripts/export-usage.mjs).
   It is COMMITTED so the page ships with data — and it is denylist-scanned
   below like every other public artifact. Missing file → empty-state page. */
let usage = null;
let usageRaw = "";
if (existsSync(join(ROOT, "usage.json"))) {
  usageRaw = read("usage.json");
  try {
    usage = JSON.parse(usageRaw);
  } catch (err) {
    console.error(`usage.json is not valid JSON: ${err.message}`);
    process.exit(1);
  }
  if (usage.schemaVersion !== 1) {
    console.error(`usage.json: unsupported schemaVersion ${usage.schemaVersion} (expected 1)`);
    process.exit(1);
  }
}

/* ── usage helpers ──────────────────────────────────────────────────────── */
const fmtInt = (n) => num(n).toLocaleString("en-US");
const fmtCompact = (n) => {
  const v = num(n);
  if (v >= 1e6) return `${(v / 1e6).toFixed(v >= 1e7 ? 0 : 1)}M`;
  if (v >= 1e3) return `${(v / 1e3).toFixed(v >= 1e4 ? 0 : 1)}k`;
  return String(v);
};
const fmtCost = (n) => `$${num(n).toFixed(2)}`;
const fmtDur = (ms) => {
  const v = num(ms);
  if (v <= 0) return "—";
  const s = Math.round(v / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${String(s % 60).padStart(2, "0")}s`;
  const h = Math.floor(m / 60);
  return `${h}h ${String(m % 60).padStart(2, "0")}m`;
};
const dayOf = (iso) => String(iso ?? "").slice(0, 10);
const fmtDay = (day) => {
  const d = new Date(`${day}T00:00:00Z`);
  return Number.isNaN(d.getTime())
    ? String(day)
    : d.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
};
const fmtDayFull = (day) => {
  const d = new Date(`${day}T00:00:00Z`);
  return Number.isNaN(d.getTime())
    ? String(day)
    : d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
};
const fmtStamp = (iso) =>
  iso && !Number.isNaN(Date.parse(iso)) ? `${String(iso).replace("T", " ").slice(0, 16)} UTC` : "—";

const USAGE_STATUS = {
  completed: { cls: "st-completed", label: "done" },
  failed: { cls: "st-failed", label: "failed" },
  running: { cls: "st-running", label: "running" },
  queued: { cls: "st-queued", label: "queued" },
  cancelled: { cls: "st-cancelled", label: "cancelled" },
};

const renderUsageStat = (stat) => `      <article class="stat-card card">
        <span class="stat-label">${esc(stat.label)}</span>
        <span class="stat-value" ${stat.count === null ? "" : `data-count="${num(stat.count)}"`}>${esc(stat.value)}</span>
        <span class="stat-sub">${esc(stat.sub)}</span>
      </article>`;

/* progress-bar row (the site's suite-bar pattern) */
const renderBarRow = (name, count, max, extra = "", title = "") => `        <div class="suite-row">
          <div class="suite-head">
            <span class="suite-name" ${title ? `title="${esc(title)}"` : ""}>${esc(name)}</span>
            <span class="suite-count">${extra}<strong>${fmtInt(count)}</strong></span>
          </div>
          <div class="bar suite-bar" role="progressbar" aria-valuenow="${num(count)}" aria-valuemin="0" aria-valuemax="${num(max)}" aria-label="${esc(name)} share">
            <div class="bar-fill" style="--w:${clamp(Math.round((num(count) / Math.max(1, num(max))) * 100), 2, 100)}%"></div>
          </div>
        </div>`;

const renderUsageEmpty = () => `  <!-- · empty state · -->
  <section class="u-section reveal" aria-labelledby="usage-empty-title">
    <div class="u-empty card">
      <span class="u-empty-ico" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v5h5"/><path d="M3.05 13A9 9 0 1 0 6 5.3L3 8"/><path d="M12 7v5l4 2"/></svg></span>
      <h2 id="usage-empty-title">No usage data yet</h2>
      <p>The usage page renders from a <code>usage.json</code> snapshot exported from the local Acute database — session counts, tokens, tool calls and sub-agent runs, with sanitized titles and hashed ids. Run the export, copy the file here, rebuild, and this page fills in.</p>
      <code>node scripts/export-usage.mjs --out usage.json</code>
      <span class="u-empty-note">run in the Acute source repo · then <code>node build.mjs</code> + commit here</span>
    </div>
  </section>`;

/* ── usage sections (rendered only when usage.json exists) ─────────────── */
let usageBody = renderUsageEmpty();
let usageSlots;

if (usage) {
  const uTotals = usage.totals ?? {};
  const tokens = uTotals.tokens ?? { input: 0, output: 0, cached: 0 };
  const usageProjects = [...(Array.isArray(usage.projects) ? usage.projects : [])];
  if (usage.unassigned) usageProjects.push(usage.unassigned);
  const hasData = usageProjects.length > 0;

  /* 01 · overview */
  const cacheRate = tokens.input > 0 ? Math.round((tokens.cached / tokens.input) * 100) : 0;
  const activeProjects = usageProjects.filter((p) => num(p.totals?.sessions) + num(p.totals?.subagents) > 0).length;
  const distinctTools = (usage.tools ?? []).length;
  const overviewStats = hasData
    ? [
        {
          label: "Projects",
          value: fmtInt(uTotals.projects),
          count: uTotals.projects,
          sub: `${activeProjects} with sessions · ${num(uTotals.projects) - activeProjects} idle`,
        },
        {
          label: "Sessions",
          value: fmtInt(uTotals.sessions),
          count: uTotals.sessions,
          sub: "main-agent chat sessions",
        },
        {
          label: "Sub-agent runs",
          value: fmtInt(uTotals.subagentSessions),
          count: uTotals.subagentSessions,
          sub: "spawned via delegate_task",
        },
        {
          label: "Tool calls",
          value: fmtInt(uTotals.toolCalls),
          count: uTotals.toolCalls,
          sub: `across ${distinctTools} distinct tools`,
        },
        {
          label: "Model requests",
          value: fmtInt(uTotals.requests),
          count: uTotals.requests,
          sub: "provider calls in the ledger",
        },
        {
          label: "Tokens sent",
          value: fmtInt(tokens.input),
          count: tokens.input,
          sub: `${fmtCompact(tokens.cached)} cached · ${cacheRate}% hit rate`,
        },
        {
          label: "Tokens received",
          value: fmtInt(tokens.output),
          count: tokens.output,
          sub: "model output tokens",
        },
        {
          label: "Est. cost",
          value: fmtCost(uTotals.costUsd),
          count: null,
          sub: num(uTotals.costUsd) > 0 ? "USD · estimated from model pricing" : "free-tier models — zero spend",
        },
      ]
    : [];

  /* 02 · activity — sessions started per UTC day (gaps filled, capped at 31) */
  const activityMap = new Map();
  for (const a of Array.isArray(usage.activity) ? usage.activity : []) {
    activityMap.set(dayOf(a.day), num(a.count));
  }
  let activityDays = [...activityMap.keys()].sort();
  let activityCapped = false;
  if (activityDays.length > 31) {
    activityDays = activityDays.slice(-31);
    activityCapped = true;
  }
  const filled = [];
  if (activityDays.length) {
    const start = Date.parse(`${activityDays[0]}T00:00:00Z`);
    const end = Date.parse(`${activityDays[activityDays.length - 1]}T00:00:00Z`);
    for (let t = start; t <= end && filled.length < 62; t += 86400000) {
      const day = new Date(t).toISOString().slice(0, 10);
      filled.push({ day, count: activityMap.get(day) ?? 0 });
    }
  }
  const maxActivity = Math.max(1, ...filled.map((d) => d.count));
  const activityCols = filled
    .map((d) => {
      const pct = Math.round((d.count / maxActivity) * 100);
      return `        <div class="u-col${d.count === 0 ? " is-zero" : ""}" role="img" aria-label="${fmtDayFull(d.day)} — ${fmtInt(d.count)} session${d.count === 1 ? "" : "s"} started">
          <span class="u-col-count">${d.count === 0 ? "·" : fmtInt(d.count)}</span>
          <div class="u-col-bar" style="height:${clamp(pct, 3, 100)}%"></div>
        </div>`;
    })
    .join("\n");
  const activityDaysRow = filled
    .map((d) => `          <span class="u-col-day">${esc(fmtDay(d.day))}</span>`)
    .join("\n");

  /* 03 · tools leaderboard */
  const maxTool = Math.max(1, ...(usage.tools ?? []).map((t) => num(t.count)));
  const toolRows = (usage.tools ?? [])
    .slice(0, 12)
    .map((t) =>
      renderBarRow(
        t.tool,
        t.count,
        maxTool,
        num(t.failures) > 0 ? `<span class="u-tool-fail" title="${num(t.failures)} failed call${num(t.failures) === 1 ? "" : "s"}">${fmtInt(t.failures)} failed · </span>` : "",
      ),
    )
    .join("\n");

  /* 04 · models */
  const modelRows = (usage.models ?? []).map((m) => {
    const tk = m.tokens ?? { input: 0, output: 0, cached: 0 };
    const calls = num(m.calls);
    const maxCalls = Math.max(1, ...(usage.models ?? []).map((x) => num(x.calls)));
    const share = clamp(Math.round((calls / maxCalls) * 100), 3, 100);
    return `      <article class="u-model-card card">
        <div class="u-model-top">
          <span class="u-model-name" title="${esc(m.model)}">${esc(m.model)}</span>
          <span class="u-model-calls">${fmtInt(calls)} call${calls === 1 ? "" : "s"}</span>
        </div>
        <div class="bar" role="progressbar" aria-valuenow="${calls}" aria-valuemin="0" aria-valuemax="${maxCalls}" aria-label="${esc(m.model)} calls relative to the busiest model">
          <div class="bar-fill" style="--w:${share}%"></div>
        </div>
        <div class="u-model-nums">
          <span class="u-model-num"><span class="u-model-num-label">Sent</span><span class="u-model-num-value" title="${fmtInt(tk.input)} tokens">${esc(fmtCompact(tk.input))}</span></span>
          <span class="u-model-num"><span class="u-model-num-label">Received</span><span class="u-model-num-value" title="${fmtInt(tk.output)} tokens">${esc(fmtCompact(tk.output))}</span></span>
          <span class="u-model-num"><span class="u-model-num-label">Cost</span><span class="u-model-num-value">${esc(fmtCost(m.costUsd))}</span></span>
        </div>
      </article>`;
  });

  /* 05 · projects → sessions → sub-agents */
  const renderSessionDetails = (s) => {
    const tk = s.tokens ?? { input: 0, output: 0, cached: 0 };
    const maxToolInSession = Math.max(1, ...(s.toolCalls ?? []).map((t) => num(t.count)));
    const toolRowsS = (s.toolCalls ?? [])
      .map(
        (t) => `          <div class="sess-toolrow">
            <span class="sess-toolname">${esc(t.tool)}</span>
            <div class="bar" role="progressbar" aria-valuenow="${num(t.count)}" aria-valuemin="0" aria-valuemax="${maxToolInSession}" aria-label="${esc(t.tool)} calls in this session">
              <div class="bar-fill" style="--w:${clamp(Math.round((num(t.count) / maxToolInSession) * 100), 4, 100)}%"></div>
            </div>
            <span class="sess-toolcount">${fmtInt(t.count)} call${num(t.count) === 1 ? "" : "s"}${num(t.failures) > 0 ? ` · <span class="u-tool-fail">${fmtInt(t.failures)} failed</span>` : ""}</span>
          </div>`,
      )
      .join("\n");
    return `        <div class="sess-body">
          <div class="sess-facts">
            <span class="sess-fact"><span class="sess-fact-label">Requests</span><span class="sess-fact-value">${fmtInt(s.requests)}</span></span>
            <span class="sess-fact"><span class="sess-fact-label">Sent ↑</span><span class="sess-fact-value" title="${fmtInt(tk.input)} tokens">${esc(fmtCompact(tk.input))}</span></span>
            <span class="sess-fact"><span class="sess-fact-label">Received ↓</span><span class="sess-fact-value" title="${fmtInt(tk.output)} tokens">${esc(fmtCompact(tk.output))}</span></span>
            <span class="sess-fact"><span class="sess-fact-label">Cached</span><span class="sess-fact-value" title="${fmtInt(tk.cached)} tokens">${esc(fmtCompact(tk.cached))}</span></span>
          </div>
          <p class="sess-meta">${esc(`Started ${fmtStamp(s.startedAt)} · ended ${fmtStamp(s.endedAt)} · ${fmtDur(s.durationMs)}`)}${s.model ? ` · <span class="mono">${esc(s.model)}</span>` : ""}</p>
          ${toolRowsS ? `          <div class="sess-toolrows">\n${toolRowsS}\n          </div>` : `          <p class="sess-meta">No tool calls recorded in this session.</p>`}
        </div>`;
  };

  const renderSubSession = (s) => {
    const st = USAGE_STATUS[s.status] ?? { cls: "st-queued", label: esc(s.status) };
    const tk = s.tokens ?? { input: 0, output: 0, cached: 0 };
    const subBadge = `sub-agent${s.role ? ` · ${esc(s.role)}` : ""}`;
    return `          <details class="sess sess-sub">
            <summary class="sess-summary">
              <span class="sess-chevron" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg></span>
              <span class="sess-sub-badge"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="3"/><circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/><line x1="10.5" y1="10" x2="6.5" y2="16"/><line x1="13.5" y1="10" x2="17.5" y2="16"/></svg>${subBadge}</span>
              <span class="sess-title" title="${esc(s.title)}">${esc(s.title)}</span>
              <span class="sess-status ${st.cls}">${st.label}</span>
              <span class="sess-nums">
                <span class="sess-num">${esc(fmtDur(s.durationMs))}</span>
                <span class="sess-num"><span class="up">↑</span> ${esc(fmtCompact(tk.input))}</span>
                <span class="sess-num"><span class="down">↓</span> ${esc(fmtCompact(tk.output))}</span>
                <span class="sess-num"><strong>${fmtInt(s.toolCallCount)}</strong> call${num(s.toolCallCount) === 1 ? "" : "s"}</span>
              </span>
            </summary>
${renderSessionDetails(s)}
          </details>`;
  };

  const renderSession = (s, subs) => {
    const st = USAGE_STATUS[s.status] ?? { cls: "st-queued", label: esc(s.status) };
    const tk = s.tokens ?? { input: 0, output: 0, cached: 0 };
    const hasSubs = subs.length > 0;
    return `        <details class="sess${hasSubs ? " has-subs" : ""}" data-sid="${esc(s.id)}">
          <summary class="sess-summary">
            <span class="sess-chevron" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg></span>
            <span class="sess-title" title="${esc(s.title)}">${esc(s.title)}</span>
            <span class="sess-status ${st.cls}">${st.label}</span>
            <span class="sess-nums">
              ${s.model ? `<span class="sess-num is-model" title="${esc(s.model)}">${esc(s.model)}</span>` : ""}
              <span class="sess-num">${esc(fmtDur(s.durationMs))}</span>
              <span class="sess-num"><span class="up" title="tokens sent">↑</span> ${esc(fmtCompact(tk.input))}</span>
              <span class="sess-num"><span class="down" title="tokens received">↓</span> ${esc(fmtCompact(tk.output))}</span>
              <span class="sess-num">${esc(fmtCost(s.costUsd))}</span>
              <span class="sess-num"><strong>${fmtInt(s.toolCallCount)}</strong> call${num(s.toolCallCount) === 1 ? "" : "s"}</span>
              ${hasSubs ? `<span class="sess-num"><strong>${subs.length}</strong> sub-agent${subs.length === 1 ? "" : "s"}</span>` : ""}
            </span>
          </summary>
${renderSessionDetails(s)}
${hasSubs ? `          <div class="sess-subwrap">\n            <span class="sess-subslabel">Delegated sub-agents</span>\n${subs.map(renderSubSession).join("\n")}\n          </div>` : ""}
        </details>`;
  };

  const renderProject = (p) => {
    const t = p.totals ?? {};
    const tk = t.tokens ?? { input: 0, output: 0, cached: 0 };
    const sessions = Array.isArray(p.sessions) ? p.sessions : [];
    const mains = sessions.filter((s) => !s.isSubagent);
    const subs = sessions.filter((s) => s.isSubagent);
    const subsByParent = new Map();
    for (const s of subs) {
      const key = s.parentId ?? "";
      if (!subsByParent.has(key)) subsByParent.set(key, []);
      subsByParent.get(key).push(s);
    }
    const sessionRows = mains
      .map((s) => renderSession(s, subsByParent.get(s.id) ?? []))
      .join("\n");
    const orphanSubs = subsByParent.get("") ?? [];
    const orphanRows = orphanSubs.map(renderSubSession).join("\n");
    const maxToolInProject = Math.max(1, ...(p.toolCalls ?? []).map((x) => num(x.count)));
    const projectToolRows = (p.toolCalls ?? [])
      .slice(0, 10)
      .map((x) => renderBarRow(x.tool, x.count, maxToolInProject, num(x.failures) > 0 ? `<span class="u-tool-fail">${fmtInt(x.failures)} failed · </span>` : ""))
      .join("\n");
    const projectModelRows = (p.models ?? [])
      .map(
        (m) => `          <div class="proj-mrow">
            <span class="proj-mname" title="${esc(m.model)}">${esc(m.model)}</span>
            <span class="proj-mnums">${fmtInt(m.calls)} call${num(m.calls) === 1 ? "" : "s"} · ↑ ${esc(fmtCompact(m.tokens?.input))} · ↓ ${esc(fmtCompact(m.tokens?.output))} · ${esc(fmtCost(m.costUsd))}</span>
          </div>`,
      )
      .join("\n");
    const hasSessions = mains.length + subs.length > 0;
    const span =
      p.firstActivity && p.lastActivity
        ? `${fmtDay(dayOf(p.firstActivity))} – ${fmtDayFull(dayOf(p.lastActivity))}`
        : "no activity";
    return `      <details class="proj card" data-pid="${esc(p.id)}">
        <summary class="proj-summary">
          <span class="proj-chevron" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg></span>
          <span class="proj-dot" style="--pc:${esc(p.color ?? "#FF6B2C")}" aria-hidden="true"></span>
          <span class="proj-name">${esc(p.name)}</span>
          ${p.synthetic ? `<span class="proj-tag">no project</span>` : ""}
          <span class="proj-meta">
            <span class="proj-chip"><strong>${fmtInt(t.sessions)}</strong> session${num(t.sessions) === 1 ? "" : "s"}</span>
            <span class="proj-chip"><strong>${fmtInt(t.subagents)}</strong> sub-agent${num(t.subagents) === 1 ? "" : "s"}</span>
            <span class="proj-chip"><strong>${fmtInt(t.toolCalls)}</strong> tool call${num(t.toolCalls) === 1 ? "" : "s"}</span>
            <span class="proj-chip" title="${fmtInt(tk.input)} sent · ${fmtInt(tk.output)} received">↑ ${esc(fmtCompact(tk.input))} · ↓ ${esc(fmtCompact(tk.output))}</span>
            <span class="proj-chip">${esc(fmtCost(t.costUsd))}</span>
            <span class="proj-chip">${esc(span)}</span>
          </span>
        </summary>
        <div class="proj-body">
${hasSessions ? `          <div class="proj-stats">
            <span class="proj-stat"><span class="proj-stat-label">Sessions</span><span class="proj-stat-value">${fmtInt(t.sessions)}</span></span>
            <span class="proj-stat"><span class="proj-stat-label">Sub-agents</span><span class="proj-stat-value">${fmtInt(t.subagents)}</span></span>
            <span class="proj-stat"><span class="proj-stat-label">Tool calls</span><span class="proj-stat-value">${fmtInt(t.toolCalls)}</span></span>
            <span class="proj-stat"><span class="proj-stat-label">Requests</span><span class="proj-stat-value">${fmtInt(t.requests)}</span></span>
            <span class="proj-stat"><span class="proj-stat-label">Sent ↑</span><span class="proj-stat-value" title="${fmtInt(tk.input)} tokens">${esc(fmtCompact(tk.input))}</span></span>
            <span class="proj-stat"><span class="proj-stat-label">Received ↓</span><span class="proj-stat-value" title="${fmtInt(tk.output)} tokens">${esc(fmtCompact(tk.output))}</span></span>
          </div>
          <div class="proj-cols">
            <div class="proj-panel">
              <div class="proj-panel-title">Tool calls</div>
              <div class="u-rows">
${projectToolRows}
              </div>
            </div>
            <div class="proj-panel">
              <div class="proj-panel-title">Models</div>
${projectModelRows || `              <p class="u-models-empty">No model calls recorded.</p>`}
            </div>
          </div>
          <h4 class="sess-heading">Sessions · ${fmtInt(t.sessions)} main + ${fmtInt(t.subagents)} sub-agent</h4>
          <div class="sess-list">
${sessionRows}
${orphanRows}
          </div>` : `          <p class="proj-nosessions">No sessions recorded for this project yet — it shows up here as soon as the first chat session lands in the database.</p>`}
        </div>
      </details>`;
  };

  const sortedProjects = [...usageProjects].sort((a, b) => {
    const key = (p) => (p.lastActivity ? Date.parse(p.lastActivity) : 0);
    return key(b) - key(a) || String(a.name).localeCompare(String(b.name));
  });
  const projectRows = sortedProjects.map(renderProject).join("\n");

  usageBody = hasData
    ? `  <!-- · 01 usage overview · -->
  <section id="overview" class="u-section reveal" aria-labelledby="usage-overview-title">
    <header class="section-head">
      <span class="section-index" aria-hidden="true">01</span>
      <div>
        <h2 id="usage-overview-title">Overview</h2>
        <p class="section-desc">The whole workspace at a glance — everything below drills into exactly these numbers.</p>
      </div>
    </header>
    <div class="stats-grid">
${overviewStats.map(renderUsageStat).join("\n")}
    </div>
  </section>

  <!-- · 02 activity · -->
  <section id="activity" class="u-section reveal" aria-labelledby="usage-activity-title">
    <header class="section-head">
      <span class="section-index" aria-hidden="true">02</span>
      <div>
        <h2 id="usage-activity-title">Activity</h2>
        <p class="section-desc">Sessions started per day, straight from session timestamps (UTC).</p>
      </div>
    </header>
    <div class="u-activity card">
      <div class="u-activity-head">
        <span class="u-activity-title">Sessions per day</span>
        <span class="u-activity-sub">${filled.length} day${filled.length === 1 ? "" : "s"} · peak ${fmtInt(maxActivity)}/day${activityCapped ? " · last 31 days" : ""}</span>
      </div>
      <div class="u-chart">
${activityCols}
      </div>
      <div class="u-cols-days">
${activityDaysRow}
      </div>
    </div>
  </section>

  <!-- · 03 tools · -->
  <section id="tools" class="u-section reveal" aria-labelledby="usage-tools-title">
    <header class="section-head">
      <span class="section-index" aria-hidden="true">03</span>
      <div>
        <h2 id="usage-tools-title">Tool usage</h2>
        <p class="section-desc">Every tool call across every project — the agent's working habits, ranked. Bars are relative to the most-used tool.</p>
      </div>
    </header>
    <div class="u-tools card">
      <div class="u-rows">
${toolRows || `        <p class="u-tools-empty">No tool calls recorded yet.</p>`}
      </div>
    </div>
  </section>

  <!-- · 04 models · -->
  <section id="models" class="u-section reveal" aria-labelledby="usage-models-title">
    <header class="section-head">
      <span class="section-index" aria-hidden="true">04</span>
      <div>
        <h2 id="usage-models-title">Models</h2>
        <p class="section-desc">The model mix behind the numbers — provider calls, token flow and cost per model.</p>
      </div>
    </header>
    <div class="u-models-grid">
${modelRows.join("\n") || `      <p class="u-models-empty">No model calls recorded yet.</p>`}
    </div>
  </section>

  <!-- · 05 projects · -->
  <section id="projects" class="u-section reveal" aria-labelledby="usage-projects-title">
    <header class="section-head">
      <span class="section-index" aria-hidden="true">05</span>
      <div>
        <h2 id="usage-projects-title">Projects &amp; sessions</h2>
        <p class="section-desc">Expand a project for its tool and model breakdown, then expand any session for the full per-session detail — sub-agent runs nest under the session that delegated them.</p>
      </div>
    </header>
    <div class="u-controls">
      <div class="u-filter" role="group" aria-label="Filter sessions">
        <button type="button" class="u-filter-btn" data-mode="all" aria-pressed="true">All sessions</button>
        <button type="button" class="u-filter-btn" data-mode="subs" aria-pressed="false">Sub-agents only</button>
      </div>
      <div class="u-bulk">
        <button type="button" class="u-bulk-btn" id="u-expand-all">Expand all</button>
        <button type="button" class="u-bulk-btn" id="u-collapse-all">Collapse all</button>
      </div>
    </div>
${projectRows}
  </section>`
    : renderUsageEmpty();

  /* usage page slots */
  const usageRangeHuman = usage.range?.from && usage.range?.to
    ? `${fmtDay(dayOf(usage.range.from))} – ${fmtDayFull(dayOf(usage.range.to))}`
    : "no activity yet";
  const usageSnapshotStamp = `snapshot ${fmtStamp(usage.generatedAt)}`;
  const usageTitle = `${product.name} — usage`;
  const usageDescription = `Detailed usage telemetry for ${product.name}: per-project and per-session tokens, tool calls, sub-agent runs, model mix and estimated cost.`;
  const usagePageUrl = `${pageUrl}usage.html`;
  const usageFooterNote =
    `Usage snapshot ${fmtStamp(usage.generatedAt)} · sanitized titles · hashed ids · zero message content · ` +
    `${esc(product.name)} v${esc(product.version)}`;
  const usageDataJson = JSON.stringify({
    buildIso,
    page: "usage",
    usage: { generatedAt: usage.generatedAt ?? null, schemaVersion: usage.schemaVersion ?? 1 },
  }).replace(/</g, "\\u003c");

  usageSlots = {
    LANG: "en",
    TITLE: esc(usageTitle),
    DESCRIPTION: esc(usageDescription),
    PAGE_URL: esc(usagePageUrl),
    FAVICON: favicon,
    CSS_URL: `assets/style.css?v=${cacheBust}`,
    USAGE_CSS_URL: `assets/usage.css?v=${cacheBust}`,
    JS_URL: `assets/app.js?v=${cacheBust}`,
    USAGE_JS_URL: `assets/usage.js?v=${cacheBust}`,
    GITHUB_URL: esc(githubUrl),
    STATUS_SHORT: esc(statusShort),
    SCHEMA_VERSION: String(usage.schemaVersion ?? 1),
    RANGE_HUMAN: esc(usageRangeHuman),
    SNAPSHOT_STAMP: esc(usageSnapshotStamp),
    TOTAL_SESSIONS_HUMAN: fmtInt(uTotals.sessions),
    TOTAL_SUBS_HUMAN: fmtInt(uTotals.subagentSessions),
    TOTAL_TOOLS_HUMAN: fmtInt(uTotals.toolCalls),
    TOTAL_TOKENS_HUMAN: esc(fmtCompact(num(tokens.input) + num(tokens.output))),
    GENERATED_STAMP: esc(fmtStamp(usage.generatedAt)),
    BUILD_STAMP: esc(buildStamp),
    USAGE_BODY: usageBody,
    FOOTER_NOTE: esc(usageFooterNote),
    DATA_JSON: usageDataJson,
  };
} else {
  /* no usage.json — empty-state page, minimal slots */
  const usageTitle = `${product.name} — usage`;
  const usageDescription = `Detailed usage telemetry for ${product.name}: per-project and per-session tokens, tool calls, sub-agent runs, model mix and estimated cost.`;
  const usagePageUrl = `${pageUrl}usage.html`;
  const usageDataJson = JSON.stringify({ buildIso, page: "usage", usage: null }).replace(/</g, "\\u003c");
  usageSlots = {
    LANG: "en",
    TITLE: esc(usageTitle),
    DESCRIPTION: esc(usageDescription),
    PAGE_URL: esc(usagePageUrl),
    FAVICON: favicon,
    CSS_URL: `assets/style.css?v=${cacheBust}`,
    USAGE_CSS_URL: `assets/usage.css?v=${cacheBust}`,
    JS_URL: `assets/app.js?v=${cacheBust}`,
    USAGE_JS_URL: `assets/usage.js?v=${cacheBust}`,
    GITHUB_URL: esc(githubUrl),
    STATUS_SHORT: esc(statusShort),
    SCHEMA_VERSION: "—",
    RANGE_HUMAN: "no data yet",
    SNAPSHOT_STAMP: "awaiting first export",
    TOTAL_SESSIONS_HUMAN: "0",
    TOTAL_SUBS_HUMAN: "0",
    TOTAL_TOOLS_HUMAN: "0",
    TOTAL_TOKENS_HUMAN: "0",
    GENERATED_STAMP: "—",
    BUILD_STAMP: esc(buildStamp),
    USAGE_BODY: usageBody,
    FOOTER_NOTE: esc(`No usage snapshot committed yet · ${esc(product.name)} v${esc(product.version)}`),
    DATA_JSON: usageDataJson,
  };
}

let usageMissing = [];
let usageHtml = usageTemplate.replace(/\{\{([A-Z0-9_]+)\}\}/g, (match, name) => {
  if (!(name in usageSlots)) {
    usageMissing.push(name);
    return match;
  }
  return usageSlots[name];
});
if (usageMissing.length) {
  console.error(`usage template placeholders without a value: ${usageMissing.join(", ")}`);
  process.exit(1);
}
const usageUnused = Object.keys(usageSlots).filter((k) => !usageTemplate.includes(`{{${k}}}`));
if (usageUnused.length) {
  console.warn(`warning: unused usage slots (fine, just informational): ${usageUnused.join(", ")}`);
}

/* ── fail-closed denylist (public site — generic classes only) ─────────── */
const DENY = [
  [/gh[pousr]_[A-Za-z0-9]{20,}/, "token pattern"],
  [/github_pat_/, "fine-grained token prefix"],
  [/sk-[A-Za-z0-9_-]{16,}/, "api-key pattern"],
  [/github\.com\/[A-Za-z0-9_.-]+:[^@\s/"']+@/, "token-in-URL"],
  [/C:\\Users\\|\/home\/[a-z]+\//, "internal filesystem path"],
  [/\b(agt_|sess_|prj_)[a-z0-9-]{6,}/i, "internal id prefix"],
  [/localhost:\d{4,5}|127\.0\.0\.1:\d{4,5}/, "dev port"],
  [/ntfy\.sh/, "notification endpoint"],
  [/github\.com\/testplay-byte\/(?!DASHBOARD)/, "link to a non-public repo"],
  [/Credential Manager|credentials\.txt/, "credential storage"],
  [/[A-Za-z0-9_]{90,}/, "suspicious secret-like run"],
];

function scan(name, content) {
  const hits = DENY.map(([re, why]) => (re.test(content) ? why : null)).filter(Boolean);
  if (hits.length) {
    console.error(`DENYLIST violation in ${name}: ${hits.join(", ")}`);
    process.exit(1);
  }
}

scan("index.html", html);
scan("assets/style.css", css);
scan("assets/app.js", js);
scan("usage.html", usageHtml);
scan("assets/usage.css", usageCss);
scan("assets/usage.js", usageJs);
if (usageRaw) {
  scan("usage.json", usageRaw);
}

/* ── write outputs ──────────────────────────────────────────────────────── */
mkdirSync(join(ROOT, "assets"), { recursive: true });
writeFileSync(join(ROOT, "index.html"), html, "utf8");
writeFileSync(join(ROOT, "assets", "style.css"), css, "utf8");
writeFileSync(join(ROOT, "assets", "app.js"), js, "utf8");
writeFileSync(join(ROOT, "usage.html"), usageHtml, "utf8");
writeFileSync(join(ROOT, "assets", "usage.css"), usageCss, "utf8");
writeFileSync(join(ROOT, "assets", "usage.js"), usageJs, "utf8");

console.log(`dashboard built`);
console.log(`  index.html         ${html.length} bytes (updated ${buildStamp})`);
console.log(`  assets/style.css   ${css.length} bytes`);
console.log(`  assets/app.js      ${js.length} bytes`);
console.log(`  usage.html         ${usageHtml.length} bytes${usage ? ` (${usageProjectsCount(usage)} project groups)` : " (empty state)"}`);
console.log(`  assets/usage.css   ${usageCss.length} bytes`);
console.log(`  assets/usage.js    ${usageJs.length} bytes`);
console.log(`  features           ${features.length} cards`);
console.log(`  documentation       ${documentation.length} cards`);
console.log(`  milestones          ${milestones.length} entries`);
console.log(`  audit               ${audit.benchmark.length} benchmark rows · ${audit.capabilities.length} capability areas · ${gapTotal} gaps · ${audit.tracks.length} tracks · ${audit.decisions.length} decisions`);
console.log(`  denylist            clean`);

function usageProjectsCount(u) {
  const n = Array.isArray(u.projects) ? u.projects.length : 0;
  return n + (u.unassigned ? 1 : 0);
}
